server:
  port: 8081

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

java:
  rest:
    waitTime: 5000
    maxRetries: 5
    exponentialGrowth: 5